version: '3'
services:
  trading_game:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - './code/:/var/www/html/trading_game/'
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - mysql_network
      - redis_network
  mysql_container:
    image: 'mysql:5.7'
    command: --innodb_use_native_aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=trading_game
      - MYSQL_DATABASE=trading_game
    ports:
      - '3306:3306'
    networks:
      - mysql_network
    volumes:
      - './mysql:/var/lib/mysql'
  redis_container:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    networks:
      - redis_network
    volumes:
      - './redis:/var/lib/redis'

networks:
  mysql_network:
    driver: bridge
  redis_network:
    driver: bridge