on: push
name: Build
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: "docker://composer:latest"
      with:
        args: "composer install -d /code"
    - uses: php-actions/phpunit@v9
    - name: PHPUnit tests
      uses: php-actions/phpunit@v9
      with:
        configuration: /code/phpunit.xml.dist
        memory_limit: 256M
